interfaces:
- description: server1
  name: Ethernet4/13
  switchport:
    mode: access
    spanning-tree:
      port_type: edge
    type: switchport
    vlan: 101
portchannel:
  channel_group_mode: active
  mtu: 9216
portchannels:
- channel_group_mode: active
  description: unity1
  members:
  - Ethernet4/11
  mtu: 9216
  switchport:
    mode: trunk
    spanning-tree:
      port_type: edge trunk
    trunk:
      native_vlan: 5
    type: switchport
    vlans_allowed:
    - 3605
    - 3607
  vpc_id: 31
- channel_group_mode: active
  description: unity2
  members:
  - Ethernet4/12
  mtu: 9216
  switchport:
    mode: trunk
    spanning-tree:
      port_type: edge trunk
    trunk:
      native_vlan: 5
    type: switchport
    vlans_allowed:
    - all
  vpc_id: 32
switchport_access:
  mode: access
  spanning-tree:
    port_type: edge
  type: switchport
  vlan: 100
switchport_trunk:
  mode: trunk
  spanning-tree:
    port_type: edge trunk
  trunk:
    native_vlan: 5
  type: switchport
  vlans_allowed:
  - all
