interfaces:
- description: server2
  name: Ethernet4/13
  switchport:
    mode: access
    spanning-tree: &id003
      port_type: edge
    type: switchport
    vlan: 105
portchannel:
  channel_group_mode: active
  mtu: 9216
portchannels:
- channel_group_mode: active
  description: unity1
  members:
  - Ethernet4/11
  mtu: 9216
  switchport:
    mode: trunk
    spanning-tree: &id001
      port_type: edge trunk
    trunk: &id002
      native_vlan: 5
    type: switchport
    vlans_allowed:
    - 3605
    - 3607
  vpc_id: 31
- channel_group_mode: active
  description: unity2
  members:
  - Ethernet4/12
  mtu: 9216
  switchport:
    mode: trunk
    spanning-tree: *id001
    trunk: *id002
    type: switchport
    vlans_allowed: &id004
    - all
  vpc_id: 32
switchport_access:
  mode: access
  spanning-tree: *id003
  type: switchport
  vlan: 100
switchport_trunk:
  mode: trunk
  spanning-tree: *id001
  trunk: *id002
  type: switchport
  vlans_allowed: *id004
